server:
  port: 80

#服务注册程序名称
spring:
  application:
    name: cloud-order-service
#eureka
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: order80-YH  #主机名称
    prefer-ip-address: true   #ip地址