server:
  port: 80


eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-provider-hystrix-order

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。
    #打开fegin对hystrix的支持
    #第一步；新建个类实现service接口，重写里面的方法（都是兜底方法）。
    #第二步：在service接口@FeignClient(value = "CLOUD-PROVIDER-HYSTRIX-PAYMENT",fallback = PaymentFallbackService.class)加fallback）
    #第三步：在主启动加@EnableHystrix

#ribbon: #如果不加这个，消费端80调8001的测试超时请求时，会报错。
  #ReadTimeout:  5000
  #ConnectTimeout: 5000
